# Generated by Django 4.1.5 on 2023-01-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specilization', models.CharField(max_length=150)),
                ('doctorname', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('maritalstatus', models.CharField(max_length=150)),
                ('visittime', models.CharField(max_length=150)),
                ('days', models.CharField(max_length=150)),
            ],
        ),
    ]
