# Generated by Django 4.1.5 on 2023-01-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='PatientAppointment',
        ),
    ]
