# Generated by Django 4.1.5 on 2023-01-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_patient_password_patient_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctorname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
