# Generated by Django 4.1.5 on 2023-01-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_diseaselist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientappointment',
            name='gender',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='symptoms',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='doctorname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
