# Generated by Django 4.1.5 on 2023-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_patientappointment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
