# Generated by Django 4.1.5 on 2023-01-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_patientappointment_age_patientappointment_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
