# Generated by Django 4.1.5 on 2023-01-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
